import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type LocaleCode = 'so' | 'en' | 'sw' | 'ar' | 'om' | 'fr';

type LanguageOption = {
  code: LocaleCode;
  label: string;
};

type LanguageContextValue = {
  locale: LocaleCode;
  direction: 'ltr' | 'rtl';
  languageOptions: LanguageOption[];
  setLocale: (locale: LocaleCode) => void;
  t: (key: string, fallback: string, vars?: Record<string, string | number>) => string;
  translateText: (value: string) => string;
};

const STORAGE_KEY = 'xiddig-language';

const languageOptions: LanguageOption[] = [
  { code: 'so', label: 'Soomaali' },
  { code: 'en', label: 'English' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'ar', label: 'العربية' },
  { code: 'om', label: 'Afaan Oromoo' },
  { code: 'fr', label: 'Francais' },
];

const uiMessages: Record<LocaleCode, Record<string, string>> = {
  so: {
    'layout.brandTagline': 'Cunto iyo adeegyo',
    'layout.deliverTo': 'Gaarsii',
    'layout.home': 'Hoyga',
    'layout.search': 'Raadi',
    'layout.orders': 'Dalabyo',
    'layout.account': 'Akoon',
    'layout.languageLabel': 'Luqad',
    'splash.kicker': 'App gaarsiin oo tayo sare leh oo Soomaaliya ah',
    'splash.title': 'Cunto, raashin, iyo waxyaabo daruuri ah oo leh socod nadiif ah oo casri ah.',
    'splash.brandLine': 'Gaarsiin Muqdisho oo heer sare ah',
    'splash.start': 'Bilow sahminta',
    'splash.slide1.title': 'Soo hel cunto Soomaali ah oo si qurux leh loo diyaariyey',
    'splash.slide1.description': 'Goob casri ah oo loogu talagalay cuntooyinka Soomaaliga, meelaha xaafadda, iyo waxyaabaha daruuriga ah.',
    'splash.slide2.title': 'Gaarsiin degdeg ah oo lagu kalsoonaan karo',
    'splash.slide2.description': 'Waqtiyo cad, dabagal nadiif ah, iyo jeeg-bixinta oo degan oo lagu kalsoon yahay.',
    'splash.slide3.title': 'Raashin iyo waxyaabaha daruuriga ah waa ku dhex jiraan',
    'splash.slide3.description': 'Ka gudub casho una gudub miro, caano, dawo, iyo agabka guriga adigoon app-ka ka bixin.',
    'splash.slide4.title': 'Prime wuxuu fududeeyaa dalabka joogtada ah',
    'splash.slide4.description': 'Gaarsiin bilaash ah, dalabyo gaar ah, iyo taageero fiican oo hal qorshe ah.',
    'home.eyebrow': 'Waxaan ka shaqeyneynaa Muqdisho',
    'home.title': 'Cunto la jeclaado iyo waxyaabaha maalinlaha ah oo leh muuqaal buluug habeenimo ah.',
    'home.description': 'Ka dhex baadh cuntooyinka Soomaaliga, fast food degdeg ah, iyo raashin hal socod oo mobile-first ah.',
    'home.openNowCount': 'Hadda furan',
    'home.fastTrackCount': 'Kuwa degdegga ah',
    'home.liveDealsCount': 'Heshiisyo nool',
    'home.centerPick': 'Xulashada dhexe',
    'home.rightNow': 'Kuwa ku dhow hadda',
    'home.searchPrompt': 'Raadi makhaayado, cuntooyin, iyo waxyaabo daruuri ah',
    'home.searchAction': 'Raadi',
    'home.categories': 'Baadh qaybaha',
    'home.seeAll': 'Eeg dhammaan',
    'home.featured': 'Caawa kuwa la xushay',
    'home.fast': 'Gaarsiin degdeg ah',
    'home.topRated': 'Kuwa ugu qiimeynta sarreeya',
    'home.primeSpotlight': 'Iftiinka Prime',
    'home.viewPrime': 'Eeg Prime',
    'home.primeActive': 'Qorshahaaga Prime wuu shaqaynayaa',
    'home.primeUpgrade': 'U gudub Prime',
    'home.primeDescription': 'Gaarsiin bilaash ah dalabyada u qalma, dalabyo gaar ah, iyo taageero mudnaan leh.',
    'home.eligibleStores': 'dukaamo u qalma',
    'home.freeDelivery': 'gaarsiin dalabyada calaamadsan',
    'home.offers': 'Dalabyo iyo heshiisyo',
    'home.groceries': 'Raashin iyo waxyaabo daruuri ah',
    'home.recent': 'Dib u dalbo iyo kuwii dhawaa',
    'search.eyebrow': 'Raadin iyo ogaansho',
    'search.title': 'Ilbiriqsiyo gudahood ka hel wax ku habboon.',
    'search.placeholder': 'Raadi makhaayado, cuntooyin, raashin',
    'search.save': 'Kaydi',
    'search.recent': 'Raadintii dhoweyd',
    'search.trending': 'Hadda caanka ah',
    'search.browse': 'Baadh cuntooyinka',
    'search.suggested': 'La soo jeediyay',
    'search.restaurants': 'Makhaayado',
    'search.noMatchesTitle': 'Makhaayado kuma habboona filtarradan.',
    'search.noMatchesBody': 'Ka saar hal ama laba filter, ama adeegsado eray raadis oo ballaaran.',
    'search.dishes': 'Soo jeedinta cuntooyinka',
    'search.filter.fast': 'Ka yar 25 daqiiqo',
    'search.filter.rating': 'Qiimeyn 4.7+',
    'search.filter.open': 'Hadda furan',
    'search.filter.prime': 'Prime u qalma',
    'search.filter.free': 'Gaarsiin bilaash ah',
    'search.filter.budget': '$$ ama ka yar',
    'category.label': 'Qayb',
    'category.notFoundTitle': 'Qaybta lama helin.',
    'category.notFoundBody': 'Ka dooro qayb kale raadinta ama ku noqo hoyga.',
    'category.backHome': 'Ku noqo hoyga',
    'category.places': '{count} meelood ayaa diyaar ah',
    'category.searchAll': 'Raadi dhammaan',
    'restaurant.notFoundTitle': 'Makhaayaddan ma aan helin.',
    'restaurant.notFoundBody': 'Isku day qayb kale ama ka raadi bogga hoyga.',
    'restaurant.explore': 'Baadh cunto',
    'restaurant.reviews': 'faallooyin',
    'restaurant.min': 'Ugu yaraan',
    'restaurant.primeEligible': 'Prime u qalma',
    'restaurant.estimatedDelivery': 'Qiyaasta gaarsiinta',
    'restaurant.deliveryFee': 'Kharashka gaarsiinta',
    'restaurant.priceLevel': 'Heerka qiimaha',
    'restaurant.inCart': 'gaariga ku jira',
    'restaurant.itemsReady': '{count} alaab ayaa diyaar ah',
    'restaurant.openCart': 'Fur gaariga',
    'restaurant.otherStoreCart': 'Gaarigu wuxuu ka yimid dukaan kale',
    'restaurant.reviewCart': 'Dib u eeg gaariga',
    'cart.emptyTitle': 'Gaarigaagu waa madhan yahay.',
    'cart.emptyBody': 'Baadh makhaayad, habbee shay, kadibna halkan ayuu kasoo muuqanayaa.',
    'cart.start': 'Bilow baadhista',
    'cart.title': 'Gaariga',
    'cart.clear': 'Nadiifi gaariga',
    'cart.details': 'Faahfaahinta gaarsiinta',
    'cart.promoCode': 'Koodhka dalabka',
    'cart.instructions': 'Tilmaamaha gaarsiinta',
    'cart.addUtensils': 'Ku dar qalabka cuntada',
    'cart.utensilsAdded': 'Qalabka cuntada waa lagu daray',
    'cart.summary': 'Soo koobidda dalabka',
    'cart.subtotal': 'Wadarta hore',
    'cart.deliveryFee': 'Kharashka gaarsiinta',
    'cart.serviceFee': 'Kharashka adeegga',
    'cart.taxes': 'Canshuuraha',
    'cart.total': 'Wadarta',
    'cart.continue': 'U gudub jeeg-bixinta',
    'cart.remove': 'Ka saar',
    'cart.standard': 'Caadi',
    'checkout.eyebrow': 'Jeeg-bixin',
    'checkout.title': 'Xaqiiji faahfaahinta gaarsiintaada.',
    'checkout.description': 'Wax walba waxay diyaar u yihiin tallaabada ugu dambeysa ee nadiifka ah oo lagu kalsoon yahay.',
    'checkout.deliveryAddress': 'Cinwaanka gaarsiinta',
    'checkout.paymentMethod': 'Habka lacag-bixinta',
    'checkout.contactInfo': 'Xogta xiriirka',
    'checkout.name': 'Magac',
    'checkout.phone': 'Telefoon',
    'checkout.driverInstructions': 'Tilmaamaha darawalka',
    'checkout.walletPhone': 'Lambarka wallet-ka',
    'checkout.walletHint': 'Waxaan kuu soo diri doonaa codsi telefoonkaaga ah. Xaqiiji lacag-bixinta si dalabkaagu u dhaqaaqo.',
    'checkout.cashHint': 'Darawalku wuxuu kuu keenayaa dalabka, adiguna waxaad ku bixinaysaa marka uu yimaado.',
    'checkout.tip': 'Sii tip gaarsiiyaha',
    'checkout.noTip': 'Tip ma jiro',
    'checkout.finalSummary': 'Soo koobidda ugu dambeysa',
    'checkout.address': 'Cinwaan',
    'checkout.payment': 'Lacag-bixin',
    'checkout.placeOrder': 'Dalabka dir',
    'checkout.free': 'Bilaash',
    'orders.eyebrow': 'Dalabyo',
    'orders.title': 'Jadwalka gaarsiintaada',
    'orders.description': 'Dalabyada nool waxay joogaan dusha. Kuwii hore waxay diyaar u yihiin dib u dalab.',
    'orders.live': 'Hadda nool',
    'orders.track': 'Raac dalabka',
    'orders.history': 'Taariikhda dalabka',
    'orders.reorder': 'Dib u dalbo',
    'orders.details': 'Eeg faahfaahin',
    'tracking.emptyTitle': 'Dalab la raacayo lama helin.',
    'tracking.emptyBody': 'Ku noqo taariikhda dalabka si aad u doorato gaarsiin kale.',
    'tracking.viewOrders': 'Eeg dalabyada',
    'tracking.liveStatus': 'Xaaladda tooska ah',
    'tracking.orderDetails': 'Faahfaahinta dalabka',
    'tracking.totalPaid': 'Wadarta la bixiyay',
    'tracking.placed': 'La dhigay',
    'tracking.items': 'Alaab',
    'tracking.back': 'Ku noqo dalabyada',
    'tracking.store': 'Dukaan',
    'tracking.courier': 'Gaarsiye',
    'tracking.you': 'Adiga',
    'profile.eyebrow': 'Akoon',
    'profile.membershipLine': 'Xubin Prime ah',
    'profile.savedAddresses': 'Cinwaannada la keydiyay',
    'profile.paymentMethods': 'Hababka lacag-bixinta',
    'profile.favorites': 'Kuwa la jecel yahay',
    'profile.preferences': 'Taageero iyo dookhyo',
    'profile.manageAddresses': 'Maamul cinwaannada',
    'profile.open': 'Fur',
    'profile.notifications': 'Ogeysiisyo',
    'profile.notificationsBody': 'Dalabyo, cusboonaysiinta dalabka, xusuusinta xubinimada',
    'profile.language': 'Luqad',
    'profile.orderHistory': 'Taariikhda dalabka',
    'profile.orderHistoryBody': '{count} dalab oo hore ayaa diyaar ah',
    'profile.view': 'Eeg',
    'profile.openPrime': 'Fur Prime',
    'profile.on': 'Shidan',
    'addresses.eyebrow': 'Cinwaannada la keydiyay',
    'addresses.title': 'Dooro halka dalabkaaga xiga uu ku degayo.',
    'addresses.addNew': 'Ku dar cinwaan cusub',
    'addresses.addNewBody': 'Ku calaamadee dhisme, xafiis, ama meel qoys oo cusub si jeeg-bixinta u sahlanaato.',
    'prime.title': 'Faa’iidooyin gaarsiin oo loogu talagalay dalabka joogtada ah.',
    'prime.description': 'Ka dhig mid nadiif ah: gaarsiin eber ah dukaamada u qalma, dalabyo gaar ah, iyo taageero fiican markaad u baahato.',
    'prime.perMonth': 'bishii',
    'prime.active': 'Xubinimada way shaqaynaysaa',
    'prime.join': 'Isku biir isla markiiba',
    'prime.partners': 'Goobaha la-hawlgalayaasha Prime',
    'prime.partnersBody': 'Makhaayadaha halka xiddigta buluugga ahi ka muuqato jeeg-bixinta.',
    'modal.close': 'Xir faahfaahinta shayga',
    'modal.required': 'Lama huraan',
    'modal.optional': 'Ikhtiyaari',
    'modal.addOns': 'Waxyaabo dheeraad ah',
    'modal.customize': 'Habbee saxankaaga',
    'modal.instructions': 'Tilmaamo gaar ah',
    'modal.placeholder': 'Suugo yar, aad u basbaas, soo wac markaad timaaddo...',
    'modal.addToCart': 'Ku dar gaariga',
    'common.free': 'Bilaash',
    'common.mobileWallet': 'Wallet-ka mobaylka',
    'common.cash': 'Lacag caddaan ah',
    'common.placeOrder': 'Dalabka dir',
    'common.confirmPhone': 'Xaqiiji telefoonka',
    'common.search': 'Raadi',
  },
  en: {},
  sw: {
    'layout.brandTagline': 'Chakula na mahitaji',
    'layout.deliverTo': 'Leta kwa',
    'layout.home': 'Nyumbani',
    'layout.search': 'Tafuta',
    'layout.orders': 'Maagizo',
    'layout.account': 'Akaunti',
    'layout.languageLabel': 'Lugha',
    'splash.kicker': 'Programu ya utoaji ya Somalia yenye ubora',
    'splash.title': 'Chakula, bidhaa za kila siku, na mahitaji ya haraka kwa mtiririko safi wa kisasa.',
    'splash.brandLine': 'Utoaji wa Mogadishu ulioboreshwa',
    'splash.start': 'Anza kuchunguza',
    'home.eyebrow': 'Tunawasilisha Mogadishu',
    'home.title': 'Chakula kizuri na mahitaji ya kila siku katika uzoefu wa kisasa wa rangi ya bluu.',
    'home.description': 'Vinjari vyakula vya Kisomali, fast food ya haraka, na bidhaa za dukani katika mtiririko mmoja wa simu.',
    'home.openNowCount': 'Zimefunguliwa sasa',
    'home.fastTrackCount': 'Njia za haraka',
    'home.liveDealsCount': 'Ofa za moja kwa moja',
    'home.centerPick': 'Chaguo la katikati',
    'home.rightNow': 'Karibu nawe sasa',
    'home.searchPrompt': 'Tafuta mikahawa, vyakula, na mahitaji',
    'home.searchAction': 'Tafuta',
    'home.categories': 'Vinjari makundi',
    'home.seeAll': 'Ona yote',
    'home.featured': 'Vilivyochaguliwa leo',
    'home.fast': 'Utoaji wa haraka',
    'home.topRated': 'Vilivyokadiriwa juu',
    'home.primeSpotlight': 'Prime',
    'home.viewPrime': 'Ona Prime',
    'home.primeActive': 'Mpango wako wa Prime uko hai',
    'home.primeUpgrade': 'Jiunge na Prime',
    'home.primeDescription': 'Utoaji bila malipo kwa oda zinazostahili, ofa maalum, na msaada wa kipaumbele.',
    'home.eligibleStores': 'maduka yanayostahili',
    'home.freeDelivery': 'utoaji kwa oda zilizoalamishwa',
    'home.offers': 'Ofa na punguzo',
    'home.groceries': 'Bidhaa za dukani na mahitaji',
    'home.recent': 'Agiza tena na ya hivi karibuni',
    'search.eyebrow': 'Utafutaji na ugunduzi',
    'search.title': 'Pata kinachofaa kwa sekunde chache.',
    'search.placeholder': 'Tafuta mikahawa, vyakula, bidhaa za dukani',
    'search.save': 'Hifadhi',
    'common.free': 'Bure',
    'common.mobileWallet': 'Wallet ya simu',
    'common.cash': 'Pesa taslimu',
  },
  ar: {
    'layout.brandTagline': 'طعام واحتياجات',
    'layout.deliverTo': 'التوصيل إلى',
    'layout.home': 'الرئيسية',
    'layout.search': 'بحث',
    'layout.orders': 'الطلبات',
    'layout.account': 'الحساب',
    'layout.languageLabel': 'اللغة',
    'splash.kicker': 'تطبيق توصيل صومالي متميز',
    'splash.title': 'طعام وبقالة واحتياجات يومية ضمن تجربة حديثة وسلسة.',
    'splash.brandLine': 'توصيل مقديشو بأسلوب راق',
    'splash.start': 'ابدأ الاستكشاف',
    'home.eyebrow': 'نوصل داخل مقديشو',
    'home.title': 'طعام مميز واحتياجات يومية بتجربة داكنة أنيقة.',
    'home.description': 'تصفح المأكولات الصومالية والوجبات السريعة والبقالة في تدفق واحد مناسب للهاتف.',
    'home.openNowCount': 'مفتوح الآن',
    'home.fastTrackCount': 'خيارات سريعة',
    'home.liveDealsCount': 'عروض مباشرة',
    'home.centerPick': 'اختيار الواجهة',
    'home.rightNow': 'بالقرب منك الآن',
    'home.searchPrompt': 'ابحث عن مطاعم وأطباق واحتياجات',
    'home.searchAction': 'بحث',
    'home.categories': 'تصفح الفئات',
    'home.seeAll': 'عرض الكل',
    'home.featured': 'مختارات الليلة',
    'home.fast': 'توصيل سريع',
    'home.topRated': 'الأعلى تقييماً',
    'home.primeSpotlight': 'برايم',
    'home.viewPrime': 'عرض برايم',
    'home.primeActive': 'عضويتك في برايم نشطة',
    'home.primeUpgrade': 'الترقية إلى برايم',
    'home.primeDescription': 'توصيل مجاني على الطلبات المؤهلة وعروض حصرية ودعم أولوية.',
    'home.eligibleStores': 'متاجر مؤهلة',
    'home.freeDelivery': 'توصيل على الطلبات المحددة',
    'home.offers': 'العروض والخصومات',
    'home.groceries': 'البقالة والاحتياجات',
    'home.recent': 'إعادة الطلب والطلبات الأخيرة',
    'search.eyebrow': 'البحث والاكتشاف',
    'search.title': 'اعثر على ما يناسبك خلال ثوانٍ.',
    'search.placeholder': 'ابحث عن مطاعم أو أطباق أو بقالة',
    'search.save': 'حفظ',
    'common.free': 'مجاني',
    'common.mobileWallet': 'محفظة هاتف',
    'common.cash': 'نقداً',
  },
  om: {
    'layout.brandTagline': 'Nyaata fi barbaachisummaa',
    'layout.deliverTo': 'Geesi',
    'layout.home': 'Mana',
    'layout.search': 'Barbaadi',
    'layout.orders': 'Ajajoota',
    'layout.account': 'Herrega',
    'layout.languageLabel': 'Afaan',
    'splash.kicker': 'App geejjibaa Somaaliyaa sadarkaa ol aanaa',
    'splash.title': 'Nyaata, bittaa mana keessaa, fi barbaachisummaa guyyaa ammayyaa fi qulqulluu ta’een.',
    'splash.brandLine': 'Geejjiba Moqdishoo fooyya’e',
    'splash.start': 'Qorachuu jalqabi',
    'home.eyebrow': 'Moqdishootti geessinaa jirra',
    'home.title': 'Nyaata gaarii fi barbaachisummaa guyyaa hundaaf muuxannoo ammayyaa.',
    'home.description': 'Nyaata Somaalee, fast food saffisaa, fi groceries keessatti marsaa tokkoon bilbilaaf qophaa’e daawwadhu.',
    'home.openNowCount': 'Amma banaa',
    'home.fastTrackCount': 'Kanneen saffisan',
    'home.liveDealsCount': 'Offers jiraatan',
    'home.centerPick': 'Filannoo giddugalaa',
    'home.rightNow': 'Siin dhihoo amma',
    'home.searchPrompt': 'Mana nyaataa, nyaata, fi barbaachisummaa barbaadi',
    'home.searchAction': 'Barbaadi',
    'home.categories': 'Ramaddiiwwan daawwadhu',
    'home.seeAll': 'Hunda ilaali',
    'home.featured': 'Har’a keessaa filataman',
    'home.fast': 'Geejjiba saffisaa',
    'home.topRated': 'Kan sadarkaa olaanaa qaban',
    'home.primeSpotlight': 'Prime',
    'home.viewPrime': 'Prime ilaali',
    'home.primeActive': 'Karoorkee Prime hojii irra jira',
    'home.primeUpgrade': 'Prime seeni',
    'home.primeDescription': 'Ajajoota irratti geejjiba bilisaa, offers adda ta’an, fi deeggarsa dursa qabu.',
    'common.free': 'Bilisaa',
    'common.mobileWallet': 'Wallet bilbilaa',
    'common.cash': 'Kaashii',
  },
  fr: {
    'layout.brandTagline': 'Repas et essentiels',
    'layout.deliverTo': 'Livrer a',
    'layout.home': 'Accueil',
    'layout.search': 'Recherche',
    'layout.orders': 'Commandes',
    'layout.account': 'Compte',
    'layout.languageLabel': 'Langue',
    'splash.kicker': 'Application de livraison premium pour la Somalie',
    'splash.title': 'Repas, courses et essentiels dans une experience moderne et fluide.',
    'splash.brandLine': 'Livraison a Mogadiscio, version premium',
    'splash.start': 'Commencer',
    'home.eyebrow': 'Livraison a Mogadiscio',
    'home.title': 'De tres bons repas et les essentiels du quotidien dans une experience moderne.',
    'home.description': 'Parcourez cuisine somalienne, fast-food et courses dans un flux unique pense pour mobile.',
    'home.openNowCount': 'Ouverts maintenant',
    'home.fastTrackCount': 'Voies rapides',
    'home.liveDealsCount': 'Offres en direct',
    'home.centerPick': 'Choix central',
    'home.rightNow': 'Pres de vous maintenant',
    'home.searchPrompt': 'Rechercher restaurants, plats et essentiels',
    'home.searchAction': 'Rechercher',
    'home.categories': 'Parcourir les categories',
    'home.seeAll': 'Voir tout',
    'home.featured': 'Selections du soir',
    'home.fast': 'Livraison rapide',
    'home.topRated': 'Les mieux notes',
    'home.primeSpotlight': 'Prime',
    'home.viewPrime': 'Voir Prime',
    'home.primeActive': 'Votre formule Prime est active',
    'home.primeUpgrade': 'Passer a Prime',
    'home.primeDescription': 'Livraison offerte sur les commandes eligibles, offres exclusives et support prioritaire.',
    'common.free': 'Gratuit',
    'common.mobileWallet': 'Portefeuille mobile',
    'common.cash': 'Especes',
  },
};

const phraseMessages: Record<LocaleCode, Record<string, string>> = {
  so: {
    'Somali food': 'Cunto Soomaali',
    'Rice dishes': 'Cunto bariis',
    'Meat & grilled': 'Hilib iyo duban',
    Breakfast: 'Quraac',
    'Tea & coffee': 'Shaah iyo qaxwo',
    'Fast food': 'Cunto degdeg ah',
    Pizza: 'Biisa',
    Chicken: 'Digaag',
    Burgers: 'Bargaro',
    Desserts: 'Macmacaanka',
    Drinks: 'Cabitaanno',
    Groceries: 'Raashin',
    Essentials: 'Waxyaabo daruuri ah',
    'Bariis, suqaar, canjeero': 'Bariis, suqaar, canjeero',
    'Mandi, bariis, bowls': 'Mandi, bariis, baaquli',
    'Goat, beef, skewers': 'Ri, lo, iyo solay',
    'Morning plates and tea': 'Suxuun subax iyo shaah',
    'Shaah, qaxwo, karak': 'Shaah, qaxwo, karak',
    'Comfort classics': 'Cuntooyin la jecel yahay',
    'Wood-fired slices': 'Qaybo foornada qoryaha',
    'Crispy and grilled': 'Qolof leh iyo duban',
    'Smash and stack': 'La jajabiyey oo la buuxiyey',
    'Sweet endings': 'Dhamaad macaan',
    'Juices and coolers': 'Casiir iyo qabow',
    'Daily essentials': 'Waxyaabaha maalinlaha ah',
    'Household and pharmacy': 'Guri iyo farmashiye',
    Home: 'Hoyga',
    Office: 'Xafiis',
    Family: 'Qoys',
    'Near Digfeer junction, blue gate': 'Agagaarka isgoyska Digfeer, albaabka buluugga ah',
    'Airport road, second floor reception': 'Wadada garoonka, soo dhoweynta dabaqa labaad',
    'Behind the pharmacy, white villa': 'Dabada farmashiyaha, villa cad',
    'Usually 14 min away': 'Badanaa 14 daqiiqo u jirta',
    'Usually 19 min away': 'Badanaa 19 daqiiqo u jirta',
    'Usually 22 min away': 'Badanaa 22 daqiiqo u jirta',
    'Cash on delivery': 'Lacag caddaan ah marka la keeno',
    'Pay when the order arrives': 'Bixi marka dalabku yimaado',
    'Approve the payment on your phone after checkout': 'Xaqiiji lacag-bixinta telefoonkaaga kadib jeeg-bixinta',
    'Use your Somtel wallet for one-step confirmation': 'Isticmaal wallet-ka Somtel si aad hal tallaabo ugu xaqiijiso',
    'Confirm instantly from your SAHAL wallet': 'Isla markiiba uga xaqiiji wallet-kaaga SAHAL',
    'Popular Somaliland wallet flow with phone approval': 'Hab wallet oo Somaliland caan ka ah oo lagu xaqiijiyo telefoonka',
    'Tonight in Mogadishu': 'Caawa Muqdisho',
    'Free delivery after sunset for Prime': 'Gaarsiin bilaash ah qorrax dhaca kadib oo Prime ah',
    'Dinner favorites, lighter checkout, and priority delivery on blue-marked spots.': 'Cashooyinka la jecel yahay, jeeg-bixin fudud, iyo gaarsiin mudnaan leh meelaha buluugga lagu calaamadeeyay.',
    'See Prime picks': 'Eeg xulashada Prime',
    'Morning rush': 'Mashquulka subaxda',
    'Breakfast in under 18 minutes': 'Quraac ka yar 18 daqiiqo',
    'Canjeero, tea, and bakery drops curated for school and office mornings.': 'Canjeero, shaah, iyo dubis loogu talagalay subaxyada iskuulka iyo xafiiska.',
    'Browse breakfast': 'Baadh quraacda',
    'Groceries and household staples in one stop': 'Raashin iyo alaabta guriga oo meel keliya ah',
    'Milk, fruit, medicine, and snacks with clean checkout and smart reorders.': 'Caano, miro, dawo, iyo cunto fudud oo leh jeeg-bixin nadiif ah iyo dib-u-dalab caqli leh.',
    'Shop essentials': 'Iibso waxyaabaha daruuriga ah',
    'Free delivery on eligible orders': 'Gaarsiin bilaash ah dalabyada u qalma',
    'Member-only offers': 'Dalabyo xubnaha oo keliya ah',
    'Priority support': 'Taageero mudnaan leh',
    'Blue-star partners unlock zero delivery fees once your basket crosses the minimum.': 'La-hawlgalayaasha xiddigta buluugga ahi waxay bixiyaan kharash gaarsiin eber ah marka gaarigaagu ka bato xadka.',
    'Prime keeps dessert boxes, breakfast drops, and weekly bundles just for subscribers.': 'Prime wuxuu kaydiyaa sanduuqyada macmacaanka, quraacda, iyo xirmooyinka toddobaadlaha ah xubnaha.',
    'Get faster issue resolution and priority replacement credits when something goes wrong.': 'Hel xal degdeg ah iyo credit beddelis mudnaan leh marka wax qaldamaan.',
    'Midweek fruit refresh': 'Cusboonaysiin miro bartamaha toddobaadka',
    'Bananas, mango, and limes packed for the week': 'Moos, cambe, iyo liin loo diyaariyey toddobaadka',
    'Night essentials': 'Waxyaabaha daruuriga ah ee habeenkii',
    'Milk, bread, snacks, and medicine cabinet basics': 'Caano, rooti, cunto fudud, iyo aasaaska armaajada daawada',
    'Order received': 'Dalabka waa la helay',
    received: 'La helay',
    Preparing: 'La diyaarinayo',
    preparing: 'La diyaarinayo',
    'Picked up': 'Waa la qaaday',
    picked_up: 'La qaaday',
    'On the way': 'Wadada ayuu ku jiraa',
    on_the_way: 'Wadada ayuu ku jiraa',
    Delivered: 'La geeyay',
    delivered: 'La geeyay',
    'We locked in your basket and sent it to the kitchen.': 'Waxaan xaqiijinay dalabkaaga oo jikada u dirnay.',
    'Your order is being packed fresh right now.': 'Dalabkaaga hadda si cusub ayaa loo diyaarinayaa.',
    'The courier has your order and is leaving the store.': 'Gaarsiiyuhu wuxuu qaaday dalabkaaga wuxuuna ka baxayaa dukaanka.',
    'The courier is getting close to your drop-off point.': 'Gaarsiiyuhu wuxuu ku soo dhowaanayaa meesha laguu keenayo.',
    'Delivered and ready to enjoy.': 'Waa la geeyay oo diyaar ayuu u yahay in la cuno.',
    Membership: 'Xubinimo',
  },
  en: {},
  sw: {
    'Somali food': 'Chakula cha Kisomali',
    Breakfast: 'Kifungua kinywa',
    Drinks: 'Vinywaji',
    Groceries: 'Bidhaa za dukani',
    Essentials: 'Mahitaji',
    Home: 'Nyumbani',
    Office: 'Ofisi',
    Family: 'Familia',
    'Cash on delivery': 'Lipa ukiletewa',
    'Pay when the order arrives': 'Lipa oda ikifika',
    'Approve the payment on your phone after checkout': 'Thibitisha malipo kwenye simu yako baada ya kukamilisha',
    'Use your Somtel wallet for one-step confirmation': 'Tumia wallet ya Somtel kuthibitisha kwa hatua moja',
    'Confirm instantly from your SAHAL wallet': 'Thibitisha mara moja kupitia wallet yako ya SAHAL',
    'Popular Somaliland wallet flow with phone approval': 'Njia maarufu ya wallet ya Somaliland yenye uthibitisho wa simu',
    Delivered: 'Imewasilishwa',
    delivered: 'Imewasilishwa',
    Membership: 'Uanachama',
  },
  ar: {
    'Somali food': 'طعام صومالي',
    Breakfast: 'فطور',
    Drinks: 'مشروبات',
    Groceries: 'بقالة',
    Essentials: 'احتياجات',
    Home: 'المنزل',
    Office: 'المكتب',
    Family: 'العائلة',
    'Cash on delivery': 'الدفع عند الاستلام',
    'Pay when the order arrives': 'ادفع عند وصول الطلب',
    'Approve the payment on your phone after checkout': 'اكد الدفع على هاتفك بعد اتمام الطلب',
    'Use your Somtel wallet for one-step confirmation': 'استخدم محفظة سومتل للتأكيد بخطوة واحدة',
    'Confirm instantly from your SAHAL wallet': 'اكد فوراً من محفظة SAHAL',
    'Popular Somaliland wallet flow with phone approval': 'مسار محفظة شائع في ارض الصومال مع تأكيد عبر الهاتف',
    Delivered: 'تم التوصيل',
    delivered: 'تم التوصيل',
    Membership: 'العضوية',
  },
  om: {
    'Somali food': 'Nyaata Somaalee',
    Breakfast: 'Qorraa irraa',
    Drinks: 'Dhugaatii',
    Groceries: 'Bittaa mana keessaa',
    Essentials: 'Barbaachisummaa',
    Home: 'Mana',
    Office: 'Waajjira',
    Family: 'Maatii',
    'Cash on delivery': 'Yeroo geeffamu kaffali',
    'Pay when the order arrives': 'Yeroo ajajni gahu kaffali',
    'Approve the payment on your phone after checkout': 'Erga xumurtee booda kaffaltii bilbila kee irratti mirkaneessi',
    'Use your Somtel wallet for one-step confirmation': 'Mirkaneessa tarkaanfii tokkoof wallet Somtel fayyadami',
    'Confirm instantly from your SAHAL wallet': 'Yeruma sana wallet SAHAL keetiin mirkaneessi',
    'Popular Somaliland wallet flow with phone approval': 'Yaad-rimee wallet Somaliland beekamaa mirkaneessa bilbilaa qabu',
    Delivered: 'Geesse',
    delivered: 'Geesse',
    Membership: 'Miseensummaa',
  },
  fr: {
    'Somali food': 'Cuisine somalienne',
    Breakfast: 'Petit-dejeuner',
    Drinks: 'Boissons',
    Groceries: 'Courses',
    Essentials: 'Essentiels',
    Home: 'Maison',
    Office: 'Bureau',
    Family: 'Famille',
    'Cash on delivery': 'Paiement a la livraison',
    'Pay when the order arrives': 'Payer a l arrivee de la commande',
    'Approve the payment on your phone after checkout': 'Validez le paiement sur votre telephone apres le paiement',
    'Use your Somtel wallet for one-step confirmation': 'Utilisez votre wallet Somtel pour une confirmation en une etape',
    'Confirm instantly from your SAHAL wallet': 'Confirmez instantanement depuis votre wallet SAHAL',
    'Popular Somaliland wallet flow with phone approval': 'Parcours wallet populaire au Somaliland avec validation sur telephone',
    Delivered: 'Livre',
    delivered: 'Livre',
    Membership: 'Abonnement',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return Object.entries(vars).reduce(
    (result, [key, value]) => result.split(`{${key}}`).join(String(value)),
    template,
  );
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<LocaleCode>('so');

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY) as LocaleCode | null;
    if (stored && languageOptions.some((option) => option.code === stored)) {
      setLocale(stored);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, locale);
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => {
    const direction = locale === 'ar' ? 'rtl' : 'ltr';

    return {
      locale,
      direction,
      languageOptions,
      setLocale,
      t: (key, fallback, vars) => interpolate(uiMessages[locale][key] ?? fallback, vars),
      translateText: (value) => phraseMessages[locale][value] ?? value,
    };
  }, [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
